import { PrismaClient } from "@prisma/client";
import { matchResume } from "./src/lib/ai/match-resume";
import { pickResume } from "./src/lib/ai/pick-resume";
import { getProfile, profileFacts } from "./src/lib/profile";
const p = new PrismaClient();
const app = await p.application.findFirst({ where: { company: { name: "Halcyon Pay" } }, include: { company: true } });
const resumes = await p.resumeVersion.findMany();
const pick = await pickResume({ jobTitle: app!.role, company: app!.company.name, jdText: app!.jdText, options: resumes.map(r => ({ id: r.id, label: r.label, kind: r.kind, specialtyNote: r.specialtyNote, preview: r.content.slice(0,600) })) });
console.log("PICKED:", resumes.find(r=>r.id===pick.id)!.label, "—", pick.reason);
const resume = resumes.find(r => r.id === pick.id)!;
const prof = await getProfile();
const { data } = await matchResume({ resumeText: resume.content, resumeLabel: resume.label, jobTitle: app!.role, company: app!.company.name, jdText: app!.jdText, candidateFacts: profileFacts(prof) });
console.log("SCORE:", data.scoreBefore, "->", data.scoreAfter);
console.log("HARD GAPS:", data.hardRequirementsGaps);
console.log("UNCLOSEABLE:", data.uncloseableGaps);
await p.$disconnect();
